"""create table DangNhap

Revision ID: c578e0240c7f
Revises: 29fe16d5f922
Create Date: 2021-12-01 12:09:34.288546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c578e0240c7f'
down_revision = '29fe16d5f922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dang_nhap',
    sa.Column('TenDangNhap', sa.String(length=200), nullable=False),
    sa.Column('MatKhau', sa.String(length=200), nullable=True),
    sa.Column('Quyen', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('TenDangNhap')
    )
    op.alter_column('khach_hang', 'Email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('khach_hang', 'Email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_table('dang_nhap')
    # ### end Alembic commands ###
